"""Webclaw Python SDK -- web extraction API client."""

from .async_client import AsyncCrawlJobHandle, AsyncWebclaw
from .client import CrawlJobHandle, Webclaw
from .errors import (
    AuthenticationError,
    NotFoundError,
    RateLimitError,
    ScopeError,
    TimeoutError,
    WebclawError,
)
from .types import (
    BatchResponse,
    BatchResult,
    BrandResponse,
    CacheInfo,
    CrawlJob,
    CrawlPage,
    CrawlStatus,
    DiscoveredEndpoint,
    EndpointKind,
    EndpointsResponse,
    ExtractResponse,
    MapResponse,
    ResearchStatusResponse,
    ScrapeResponse,
    SearchAppliedFilters,
    SearchFreshness,
    SearchResponse,
    SummarizeResponse,
    WatchCheckResponse,
    WatchEntry,
    WatchSnapshot,
    WatchDetail,
    WatchListResponse,
    XAudienceResponse,
    XAudienceUser,
    XMonitor,
    XMonitorKind,
    XMonitorListResponse,
    YouTubeData,
)

__all__ = [
    # clients
    "Webclaw",
    "AsyncWebclaw",
    "CrawlJobHandle",
    "AsyncCrawlJobHandle",
    # types
    "BatchResponse",
    "BatchResult",
    "BrandResponse",
    "CacheInfo",
    "CrawlJob",
    "CrawlPage",
    "CrawlStatus",
    "DiscoveredEndpoint",
    "EndpointKind",
    "EndpointsResponse",
    "ExtractResponse",
    "MapResponse",
    "ResearchStatusResponse",
    "ScrapeResponse",
    "SearchAppliedFilters",
    "SearchFreshness",
    "SearchResponse",
    "SummarizeResponse",
    "WatchCheckResponse",
    "WatchEntry",
    "WatchSnapshot",
    "WatchDetail",
    "WatchListResponse",
    "XAudienceResponse",
    "XAudienceUser",
    "XMonitor",
    "XMonitorKind",
    "XMonitorListResponse",
    "YouTubeData",
    # errors
    "WebclawError",
    "AuthenticationError",
    "ScopeError",
    "RateLimitError",
    "NotFoundError",
    "TimeoutError",
]
